"""The systemd user unit, generated rather than pasted.

A unit file is mostly boilerplate, so the temptation is to paste one into the
README and let the reader edit the paths. Two things here argue against that.

**The paths are knowable.** ``wcsd`` knows where it is installed, and which of
``qdbus``/``gdbus``/``busctl`` this machine actually has. A generated unit
needs no editing at all, which is the same reason the udev rule is generated
from the roles udev assigned rather than from a template with a vendor id in
it.

**The start ordering guards a silent failure.** ``Daemon._load_script`` logs a
failure to load the KWin feed script and carries on, because a compositor that
has gone away mid-session is not a reason to take the daemon down with it. The
cost is that a daemon started *before* KWin answers on the session bus looks
perfectly healthy and receives nothing -- the exact shape of failure this
project has already spent two sessions bisecting. ``After=`` probably covers
it; ``ExecStartPre`` makes it certain, and costs one wasted D-Bus call when it
was already fine.

Nothing here writes to ``~/.config/systemd``: like ``--write-config`` and
``--write-rule``, the text goes to stdout and installing it is an explicit
choice made by the reader.
"""

from __future__ import annotations

import os
import shlex
import shutil
from pathlib import Path
from typing import Optional, Sequence

from .kwinscript import KWIN_SERVICE, SCRIPTING_PATH

UNIT_NAME = "wayland-cursor-smoother.service"

#: The unit that owns the compositor on Plasma 6 Wayland. Ordering after it is
#: what makes the readiness wait below usually redundant.
KWIN_UNIT = "plasma-kwin_wayland.service"

#: Seconds to wait for KWin's scripting interface before giving up and letting
#: the start fail. Generous: a cold session with many outputs can take a while,
#: and failing loudly after half a minute beats running deaf for an afternoon.
READY_TIMEOUT = 30


def default_unit_path() -> Path:
    base = os.environ.get("XDG_CONFIG_HOME") or os.path.expanduser("~/.config")
    return Path(base) / "systemd" / "user" / UNIT_NAME


def readiness_command(program: Optional[str] = None) -> list[str]:
    """A command that exits 0 once KWin's scripting interface will answer.

    `program` is a path to whichever D-Bus command line tool was found --
    :func:`wcs.kwinscript.find_dbus_caller` picks the same one the daemon will
    use to load the script, so a machine where the gate passes is a machine
    where the load works. `busctl` is the fallback because systemd ships it,
    and we are writing a systemd unit.
    """
    name = Path(program).name if program else ""
    if name.startswith("qdbus"):
        return [program, KWIN_SERVICE, SCRIPTING_PATH]
    if name.startswith("gdbus"):
        return [program, "introspect", "--session",
                "--dest", KWIN_SERVICE, "--object-path", SCRIPTING_PATH]
    return [shutil.which("busctl") or "/usr/bin/busctl",
            "--user", "introspect", KWIN_SERVICE, SCRIPTING_PATH]


def _tool(name: str, fallback: str) -> str:
    return shutil.which(name) or fallback


def service_text(exec_start: Sequence[str], *,
                 ready: Optional[Sequence[str]] = None,
                 timeout: int = READY_TIMEOUT) -> str:
    """Render the unit. Every path is absolute and no systemd specifier (`%h`
    and friends) appears, so what is read is what runs."""
    if ready is None:
        ready = readiness_command()
    wait = "until {} > /dev/null 2>&1; do sleep 0.5; done".format(
        shlex.join(list(ready)))
    return f"""\
# wayland-cursor-smoother -- systemd user unit
#
# Generated by `wcsd --write-service`, which bakes in the absolute paths this
# machine has. Regenerate it rather than editing it if the checkout moves.
#
#   systemctl --user daemon-reload
#   systemctl --user enable --now {UNIT_NAME}
#   journalctl --user -u {UNIT_NAME} -f

[Unit]
Description=wayland-cursor-smoother: slide the pointer past the gaps in a layout
Documentation=https://github.com/beatenavenue/wayland-cursor-smoother
# Stops with the session rather than lingering after it.
PartOf=graphical-session.target
After={KWIN_UNIT}

[Service]
Type=simple
# The daemon logs a failure to load its KWin feed script and carries on, so a
# start that wins the race against KWin produces a process that looks healthy
# and receives nothing. After= above should already prevent that; this makes
# it certain, and wastes one D-Bus call when it was never in doubt.
ExecStartPre={_tool("timeout", "/usr/bin/timeout")} {timeout} {_tool("sh", "/bin/sh")} -c '{wait}'
ExecStart={shlex.join(list(exec_start))}
# Re-read the display layout after rearranging monitors, without dropping the
# virtual pointer or the feed script:
#     systemctl --user reload wayland-cursor-smoother
ExecReload={_tool("kill", "/bin/kill")} -HUP $MAINPID
Restart=on-failure
# A second copy started by hand exits 2 because the bus name is taken. Five
# seconds is long enough that such a start does not spin.
RestartSec=5
TimeoutStopSec=10

[Install]
WantedBy=graphical-session.target
"""


def install_commands(path: Path) -> list[str]:
    return [
        "systemctl --user daemon-reload",
        f"systemctl --user enable --now {UNIT_NAME}",
        f"journalctl --user -u {UNIT_NAME} -f",
    ] if path == default_unit_path() else [
        f"install -Dm644 {path} {default_unit_path()}",
        "systemctl --user daemon-reload",
        f"systemctl --user enable --now {UNIT_NAME}",
        f"journalctl --user -u {UNIT_NAME} -f",
    ]
